

[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#ea76cb"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#edb4e0"
playing_selected = "#40a02b"
error = "#4c4f69"
error_bg = "#d20f39"
statusbar = "#ea76cb"
statusbar_bg = "#ccd0da"
statusbar_progress = "#ea76cb"
cmdline = "#ea76cb"
cmdline_bg = "#e6e9ef"
