[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#c6a0f6"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#756498"
playing_selected = "#a6da95"
error = "#24273a"
error_bg = "#ed8796"
statusbar = "#c6a0f6"
statusbar_bg = "#363a4f"
statusbar_progress = "#c6a0f6"
cmdline = "#c6a0f6"
cmdline_bg = "#1e2030"
