[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#d20f39"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#e18097"
playing_selected = "#40a02b"
error = "#eff1f5"
error_bg = "#d20f39"
statusbar = "#d20f39"
statusbar_bg = "#ccd0da"
statusbar_progress = "#d20f39"
cmdline = "#d20f39"
cmdline_bg = "#e6e9ef"
