

[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#df8e1d"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#e7c089"
playing_selected = "#40a02b"
error = "#4c4f69"
error_bg = "#d20f39"
statusbar = "#df8e1d"
statusbar_bg = "#ccd0da"
statusbar_progress = "#df8e1d"
cmdline = "#df8e1d"
cmdline_bg = "#e6e9ef"
