

[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#1e66f5"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#87acf5"
playing_selected = "#40a02b"
error = "#4c4f69"
error_bg = "#d20f39"
statusbar = "#1e66f5"
statusbar_bg = "#ccd0da"
statusbar_progress = "#1e66f5"
cmdline = "#1e66f5"
cmdline_bg = "#e6e9ef"
