[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#04a5e5"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#7acbed"
playing_selected = "#40a02b"
error = "#eff1f5"
error_bg = "#d20f39"
statusbar = "#04a5e5"
statusbar_bg = "#ccd0da"
statusbar_progress = "#04a5e5"
cmdline = "#04a5e5"
cmdline_bg = "#e6e9ef"
