

[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#f4b8e4"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#927695"
playing_selected = "#a6d189"
error = "#c6d0f5"
error_bg = "#e78284"
statusbar = "#f4b8e4"
statusbar_bg = "#414559"
statusbar_progress = "#f4b8e4"
cmdline = "#f4b8e4"
cmdline_bg = "#292c3c"
