[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#e78284"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#8b5b65"
playing_selected = "#a6d189"
error = "#303446"
error_bg = "#e78284"
statusbar = "#e78284"
statusbar_bg = "#414559"
statusbar_progress = "#e78284"
cmdline = "#e78284"
cmdline_bg = "#292c3c"
