[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#ef9f76"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#8f695e"
playing_selected = "#a6d189"
error = "#303446"
error_bg = "#e78284"
statusbar = "#ef9f76"
statusbar_bg = "#414559"
statusbar_progress = "#ef9f76"
cmdline = "#ef9f76"
cmdline_bg = "#292c3c"
