[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#81c8be"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#587e82"
playing_selected = "#a6d189"
error = "#303446"
error_bg = "#e78284"
statusbar = "#81c8be"
statusbar_bg = "#414559"
statusbar_progress = "#81c8be"
cmdline = "#81c8be"
cmdline_bg = "#292c3c"
