[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#dd7878"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#e6b5b7"
playing_selected = "#40a02b"
error = "#eff1f5"
error_bg = "#d20f39"
statusbar = "#dd7878"
statusbar_bg = "#ccd0da"
statusbar_progress = "#dd7878"
cmdline = "#dd7878"
cmdline_bg = "#e6e9ef"
