[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#ca9ee6"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#7d6996"
playing_selected = "#a6d189"
error = "#303446"
error_bg = "#e78284"
statusbar = "#ca9ee6"
statusbar_bg = "#414559"
statusbar_progress = "#ca9ee6"
cmdline = "#ca9ee6"
cmdline_bg = "#292c3c"
