

[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#179299"
title = "#fe640b"
playing = "#40a02b"
playing_bg = "#eff1f5"
highlight = "#4c4f69"
highlight_bg = "#f7ab80"
playing_selected = "#40a02b"
error = "#4c4f69"
error_bg = "#d20f39"
statusbar = "#fe640b"
statusbar_bg = "#ccd0da"
statusbar_progress = "#fe640b"
cmdline = "#fe640b"
cmdline_bg = "#e6e9ef"
