[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#94e2d5"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#598081"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#94e2d5"
statusbar_bg = "#313244"
statusbar_progress = "#94e2d5"
cmdline = "#94e2d5"
cmdline_bg = "#181825"
