[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#f9e2af"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#8b806e"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#f9e2af"
statusbar_bg = "#313244"
statusbar_progress = "#f9e2af"
cmdline = "#f9e2af"
cmdline_bg = "#181825"
