[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#f0c6c6"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#8a7780"
playing_selected = "#a6da95"
error = "#24273a"
error_bg = "#ed8796"
statusbar = "#f0c6c6"
statusbar_bg = "#363a4f"
statusbar_progress = "#f0c6c6"
cmdline = "#f0c6c6"
cmdline_bg = "#1e2030"
