[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#a6da95"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#658167"
playing_selected = "#a6da95"
error = "#24273a"
error_bg = "#ed8796"
statusbar = "#a6da95"
statusbar_bg = "#363a4f"
statusbar_progress = "#a6da95"
cmdline = "#a6da95"
cmdline_bg = "#1e2030"
