

[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#f5c2e7"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#89708a"
playing_selected = "#a6e3a1"
error = "#cdd6f4"
error_bg = "#f38ba8"
statusbar = "#f5c2e7"
statusbar_bg = "#313244"
statusbar_progress = "#f5c2e7"
cmdline = "#f5c2e7"
cmdline_bg = "#181825"
