[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#b7bdf8"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#6d7299"
playing_selected = "#a6da95"
error = "#24273a"
error_bg = "#ed8796"
statusbar = "#b7bdf8"
statusbar_bg = "#363a4f"
statusbar_progress = "#b7bdf8"
cmdline = "#b7bdf8"
cmdline_bg = "#1e2030"
