[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#ee99a0"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#89606d"
playing_selected = "#a6da95"
error = "#24273a"
error_bg = "#ed8796"
statusbar = "#ee99a0"
statusbar_bg = "#363a4f"
statusbar_progress = "#ee99a0"
cmdline = "#ee99a0"
cmdline_bg = "#1e2030"
