

[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#f5a97f"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#8c685c"
playing_selected = "#a6da95"
error = "#cad3f5"
error_bg = "#ed8796"
statusbar = "#f5a97f"
statusbar_bg = "#363a4f"
statusbar_progress = "#f5a97f"
cmdline = "#f5a97f"
cmdline_bg = "#1e2030"
