

[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#e5c890"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#8a7e6b"
playing_selected = "#a6d189"
error = "#c6d0f5"
error_bg = "#e78284"
statusbar = "#e5c890"
statusbar_bg = "#414559"
statusbar_progress = "#e5c890"
cmdline = "#e5c890"
cmdline_bg = "#292c3c"
