

[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#fab387"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#8c685a"
playing_selected = "#a6e3a1"
error = "#cdd6f4"
error_bg = "#f38ba8"
statusbar = "#fab387"
statusbar_bg = "#313244"
statusbar_progress = "#fab387"
cmdline = "#fab387"
cmdline_bg = "#181825"
