

[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#eebebe"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#8f7982"
playing_selected = "#a6d189"
error = "#c6d0f5"
error_bg = "#e78284"
statusbar = "#eebebe"
statusbar_bg = "#414559"
statusbar_progress = "#eebebe"
cmdline = "#eebebe"
cmdline_bg = "#292c3c"
