

[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#f2cdcd"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#88757d"
playing_selected = "#a6e3a1"
error = "#cdd6f4"
error_bg = "#f38ba8"
statusbar = "#f2cdcd"
statusbar_bg = "#313244"
statusbar_progress = "#f2cdcd"
cmdline = "#f2cdcd"
cmdline_bg = "#181825"
