

[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#8bd5ca"
title = "#eed49f"
playing = "#a6da95"
playing_bg = "#24273a"
highlight = "#cad3f5"
highlight_bg = "#897e6c"
playing_selected = "#a6da95"
error = "#cad3f5"
error_bg = "#ed8796"
statusbar = "#eed49f"
statusbar_bg = "#363a4f"
statusbar_progress = "#eed49f"
cmdline = "#eed49f"
cmdline_bg = "#1e2030"
